project_id = "kgkjrxwoojykdebtgutf"

[functions.validate-invite]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.send-aula-notification]
verify_jwt = true

[functions.send-aula-reminder]
verify_jwt = false