// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgkjrxwoojykdebtgutf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtna2pyeHdvb2p5a2RlYnRndXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzY2OTcsImV4cCI6MjA3Mzk1MjY5N30.MJRmYLNO7Cwfg_rhLza1ukwS-h5jLSKYTaYZ7VSfF-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});